apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 80              # Port exposed by the service inside the cluster
      targetPort: 3000      # Port inside the container
      nodePort: 30080       # Port on the node (external)
  type: NodePort
